name: Deploy to Remote Server

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    branches: [master, main]
    types:
      - completed

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    
    environment:
      name: production
    
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
      CONTAINER_NAME: github-action-app
      HOST_PORT: 3300
      CONTAINER_PORT: 3000
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DEPLOY_PATH: /home/anisafifi/auriga/github-action-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Prepare remote deploy directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          envs: DEPLOY_PATH
          script: |
            set -e
            mkdir -p "$DEPLOY_PATH"

      - name: Upload docker compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: docker-compose.yml
          target: ${{ env.DEPLOY_PATH }}

      - name: Create .env file and Deploy with Docker Compose over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME,HOST_PORT,CONTAINER_PORT,GHCR_USERNAME,GHCR_TOKEN,DEPLOY_PATH
          script: |
            set -e
            cd "$DEPLOY_PATH"

            # Create .env file for Docker Compose
            cat > .env <<EOF
              IMAGE_NAME=$IMAGE_NAME
              CONTAINER_NAME=$CONTAINER_NAME
              HOST_PORT=$HOST_PORT
              CONTAINER_PORT=$CONTAINER_PORT
              GHCR_USERNAME=$GHCR_USERNAME
              GHCR_TOKEN=$GHCR_TOKEN
              EOF

            # Login to GitHub Container Registry
            sudo docker login ghcr.io -u "$GHCR_USERNAME" -p "$GHCR_TOKEN"

            # Pull and deploy
            sudo docker compose -f docker-compose.yml pull
            sudo docker compose -f docker-compose.yml up -d --remove-orphans